"""Write acap/app/model_params.h from the exported TFLite model.

The model has two outputs (the graph is cut before YOLOv8's final Concat):
  boxes  1 x 4  x N  - cx, cy, w, h in model-input pixels
  scores 1 x 80 x N  - sigmoid'd per-class scores, no objectness
They are told apart by channel count, not by index, because ordering is not
guaranteed.

The header records the model's sha256 so acap/build.sh can refuse to build a
header and a model that have drifted apart.

  python tools/parameter_finder.py model/yolov8n_640_int8.tflite [out.h]

Needs an interpreter: ai-edge-litert (small) or tensorflow (large).
"""
import hashlib
import sys

try:
    from ai_edge_litert.interpreter import Interpreter
except ImportError:  # pragma: no cover - fallback for a full-TF environment
    from tensorflow.lite import Interpreter

if len(sys.argv) < 2:
    sys.exit("usage: parameter_finder.py MODEL.tflite [OUT.h]")

model_path = sys.argv[1]
out_path = sys.argv[2] if len(sys.argv) > 2 else "acap/app/model_params.h"

interpreter = Interpreter(model_path)
interpreter.allocate_tensors()
inp = interpreter.get_input_details()[0]
outs = interpreter.get_output_details()

if len(outs) != 2:
    sys.exit(f"Error: expected 2 output tensors, model has {len(outs)}.")

model_input_height = int(inp["shape"][1])
model_input_width = int(inp["shape"][2])

box = next(o for o in outs if o["shape"][1] == 4)
score = next(o for o in outs if o["shape"][1] != 4)

box_scale, box_zp = box["quantization"]
score_scale, score_zp = score["quantization"]
num_classes = int(score["shape"][1])
num_detections = int(score["shape"][2])

if int(box["shape"][2]) != num_detections:
    sys.exit("Error: box and score tensors disagree on the anchor count.")

with open(model_path, "rb") as f:
    digest = hashlib.sha256(f.read()).hexdigest()

with open(out_path, "w") as f:
    f.write(f"""/* Generated by tools/parameter_finder.py from {model_path}.
 * Committed on purpose: the model is committed too, so there is no reason for
 * every build to pull a 2 GB TensorFlow image to re-read four numbers.
 * Regenerate with tools/export_yolov8.sh, which runs the finder at the end.
 * acap/build.sh checks the model hash against the digest below and refuses
 * to build if this header and the model have drifted apart.
 *
 * MODEL_SHA256 {digest}
 */
#ifndef MODEL_PARAMS_H
#define MODEL_PARAMS_H

#define MODEL_INPUT_HEIGHT {model_input_height}
#define MODEL_INPUT_WIDTH {model_input_width}

/* I/O is {inp["dtype"].__name__}; larod's convert preprocessor feeds the model directly. */
#define BOX_QUANT_SCALE {box_scale}f
#define BOX_QUANT_ZERO_POINT {box_zp}
#define SCORE_QUANT_SCALE {score_scale}f
#define SCORE_QUANT_ZERO_POINT {score_zp}

#define NUM_CLASSES {num_classes}
#define NUM_DETECTIONS {num_detections}

#endif  // MODEL_PARAMS_H
""")

print(f"{out_path}: input {model_input_width}x{model_input_height} {inp['dtype'].__name__}")
print(f"  box   scale={box_scale} zp={box_zp}")
print(f"  score scale={score_scale} zp={score_zp} classes={num_classes} anchors={num_detections}")
print(f"  sha256 {digest}")
