/* YOLOv8 Detector for AXIS cameras
 * Copyright (C) 2026 Pavel Kotyza <kotyza@gmail.com> - AGPL-3.0, see LICENSE
 *
 * Generated by tools/parameter_finder.py from model/yolov8n_384x640_uint8.tflite.
 * Committed on purpose: the model is committed too, so there is no reason for
 * every build to pull a 2 GB TensorFlow image to re-read four numbers.
 * Regenerate with tools/export_yolov8.sh, which runs the finder at the end.
 * acap/build.sh checks the model hash against the digest below and refuses
 * to build if this header and the model have drifted apart.
 *
 * MODEL_SHA256 0357c7808b3d20a4fecb0506dc2accec510c4c57e4f79a28fdb16f81790aaf7e
 */
#ifndef MODEL_PARAMS_H
#define MODEL_PARAMS_H

#define MODEL_INPUT_HEIGHT 384
#define MODEL_INPUT_WIDTH 640

/* I/O is uint8; larod's convert preprocessor feeds the model directly. */
#define BOX_QUANT_SCALE 2.5369834899902344f
#define BOX_QUANT_ZERO_POINT 0
#define SCORE_QUANT_SCALE 0.00390625f
#define SCORE_QUANT_ZERO_POINT 0

#define NUM_CLASSES 80
#define NUM_DETECTIONS 5040

#endif  // MODEL_PARAMS_H
