/* Generated by tools/parameter_finder.py from model/yolov8n_640_int8.tflite.
 * Committed on purpose: the model is committed too, so there is no reason for
 * every build to pull a 2 GB TensorFlow image to re-read four numbers.
 * Regenerate with tools/export_yolov8.sh, which runs the finder at the end.
 * acap/build.sh checks the model hash against the digest below and refuses
 * to build if this header and the model have drifted apart.
 *
 * MODEL_SHA256 b1a8a805508d9380154f2cb11f002c72ac44debdaea799399a721366b0af7b26
 */
#ifndef MODEL_PARAMS_H
#define MODEL_PARAMS_H

#define MODEL_INPUT_HEIGHT 640
#define MODEL_INPUT_WIDTH 640

/* uint8 I/O, not int8: larod's convert preprocessor feeds the model directly. */
#define BOX_QUANT_SCALE 2.5758814811706543f
#define BOX_QUANT_ZERO_POINT 0
#define SCORE_QUANT_SCALE 0.00390625f
#define SCORE_QUANT_ZERO_POINT 0

#define NUM_CLASSES 80
#define NUM_DETECTIONS 8400

#endif  // MODEL_PARAMS_H
